#!/usr/bin/env zsh

successfully() {
  $* || (echo "failed" 1>&2 && exit 1)
}

echo "Installing rbenv, Simple Ruby Version Management ..."
  successfully brew install rbenv
  successfully echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bash_profile
  successfully echo 'eval "$(rbenv init -)"' >> ~/.bash_profile
  successfully exec $SHELL

echo "Installing ruby-build - an rbenv plugin that provides an rbenv install ..."
  successfully brew install ruby-build

echo "Installing Ruby 1.9.3-p194 ..."
  successfully rbenv install 1.9.3-p194
  successfully rbenv rehash
# echo "Installing RVM (Ruby Version Manager) and Ruby 1.9.3, which becomes the default ..."
#   successfully curl -L https://get.rvm.io | bash -s -- --version 1.15.10 --ruby
#   successfully echo "
# # RVM
# [[ -s '/Users/`whoami`/.rvm/scripts/rvm' ]] && source '/Users/`whoami`/.rvm/scripts/rvm'" >> ~/.zshenv
#   successfully source ~/.zshenv

echo "Installing Bundler to build gem dependencies ..."
  successfully gem install bundler --no-rdoc --no-ri

echo "Installing Rails to write and run web applications ..."
  successfully gem install rails --no-rdoc --no-ri

# echo "Installing the Heroku gem to interact with the http://heroku.com API ..."
#   successfully gem install heroku --no-rdoc --no-ri

# echo "Installing the pg gem to talk to Postgres databases ..."
#   successfully gem install pg --no-rdoc --no-ri

# echo "Installing the foreman gem for serving your Rails apps in development mode ..."
#   successfully gem install foreman --no-rdoc --no-ri

# echo "Installing the heroku-config plugin for pulling config variables locally to be used as ENV variables ..."
#   successfully heroku plugins:install git://github.com/ddollar/heroku-config.git
